# -*- coding: utf-8 -*-
"""Copy of CropPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ilAkzhsaZJ2RH4wBkpdCNOkGAmJAiBH
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from tensorflow import keras
import numpy as np

dataset = pd.read_csv('/content/drive/My Drive/Project/dataset/crop_production.csv')
dataset

"""# New Section"""

len(set(dataset['Crop']))

season_encoder = dict(zip([i.strip() for i in sorted(set(dataset['Season']))],range(1,len(set(dataset['Season']))+1)))
state_encoder = dict(zip([i.strip() for i in sorted(set(dataset['State_Name']))], range(1,len(set(dataset['State_Name']))+1)))
print(season_encoder,"\n", state_encoder)

seasons=[season_encoder[i.strip()]/len(season_encoder.keys()) for i in list(dataset['Season'])]
states=[state_encoder[i.strip()]/len(state_encoder.keys()) for i in list(dataset['State_Name'])]
avg=sum(dataset['Area'])/len(dataset['Area'])
area = [i/avg for i in list(dataset['Area'])]
train_data = np.array([[i,j,k] for (i,j,k) in zip(seasons, states, area)], ndmin=2)

model=keras.Sequential([
                  keras.layers.Input(3),
                  keras.layers.Dense(200, activation='relu'),
                  keras.layers.Dense(124,activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

crops_encoder = dict(zip([i.strip() for i in sorted(set(dataset['Crop']))], range(0,len(set(dataset['Crop'])))))
crops=np.array([crops_encoder[c.strip()] for c in list(dataset['Crop'])])
print(crops.shape)

a=[100,100]
for x in a:
  model.fit(train_data, crops, epochs=x)

model.predict(train_data , batch_size=16)